### ISSUE TITLE
Extracting data of requests 

### ISSUE THREAD

**Issue by perriea** [hadrianl/ibapi#11]
How extracting data of request ? 
In the past, I used [gofinance/ib](https://github.com/gofinance/ib), it was easy to extract the data of my requests. Can you tell me how to do and document this ?

**Example** : 
reqContract -> struct Contract
etc...

**Comment by hadrianl** [comment]
@perriea u could define your own wrapper that implements ibapi.IbWrapper interface.
The demo wrapper just info the data delivered by tws or gateway

**Comment by perriea** [comment]
ahhh ! It's really cool !
Do you plan to maintain it over time ? I can help if necessary.

**Comment by hadrianl** [comment]
yep， appreciate it if you could help with this.
Generally, I would like to stick with Interactive broker official implement.
And improve performance base on this.
right now ,i'm doing some work with the fully test
