### ISSUE TITLE
ReqHistoricalData() example?

### ISSUE THREAD

**Issue by fiber** [hadrianl/ibapi#13]
I can't get ReqHistoricalData() to work. Do you have an example?

	c := ibapi.Contract{ContractID: 309359839, Symbol: "HSI", SecurityType: "FUT", Exchange: "HKFE"}
	ic.ReqMarketDataType(3)
	ic.ReqHistoricalData(ic.GetReqID(), &c, "", "1 W", "1 D", "MIDPOINT", false, 1, true, nil)

**Comment by hadrianl** [comment]
u could get the official doc [right here](http://interactivebrokers.github.io/tws-api/historical_bars.html)

**Comment by hadrianl** [comment]
data would deliver via wrapper.HistoricalData()

**Comment by hadrianl** [comment]
it seems that u got an invalid bar sizes "1 D".
it should be "1 day"

**Comment by fiber** [comment]
I got this to work. It's essential to have a subscription for market data. I had meant to access delayed data without a subscription, which does not work.

**Comment by hadrianl** [comment]
1.ReqHistoricalData always require a subscription, set the market data type won't work for historical data
2.ReqMktData will work with this
3.if you already subscribed the market data, it will always return live data even though you requested delayed data
4.if you did ReqMktData right after ReqMarketDataType, that may not work properly.TWS or  gateway might have not set the market data type to delayed before it got ReqMarketDataType. So, ReqMarketDataType after wrapper.MarketDataType callback is better.
