### ISSUE TITLE
CP Web gateway

### ISSUE THREAD

**Issue by sachinbhutani** [hadrianl/ibapi#15]
can it work with CP web gateway ? 
https://interactivebrokers.github.io/cpwebapi/index.html#login

**Comment by hadrianl** [comment]
No, ibapi is just for IB TWS or IB Gateway.

**Comment by sachinbhutani** [comment]
thanks. I started https://github.com/sachinbhutani/goibcp

**Comment by hadrianl** [comment]
@sachinbhutani great job!!!!!
