### ISSUE TITLE
Decode error when requesting completed orders

### ISSUE THREAD

**Issue by rcalin** [hadrianl/ibapi#17]
When firing `m.Client.ReqCompletedOrders` method,  a decode error is generated when parsing the reply: `{"level":"error","ts":1600076419.379908,"caller":"ibapi/client.go:2934","msg":"decoder got unexpected error","error":"interface conversion: string is not error: missing method Error",`

Server version: **115**
IBGW version: **978**

**Comment by hadrianl** [comment]
thx, I have figured out what's wrong with it.
I would fix it as soon as possible

**Comment by rcalin** [comment]
awesome, thanks!
