### ISSUE TITLE
Order ID and price are not populated correctly for CompletedOrders Reply

### ISSUE THREAD

**Issue by rcalin** [hadrianl/ibapi#18]
Hi, 

The Completed Orders req is now working, however it seems that Order ID and price are not populated correctly for the CompletedOrders reply:
`"msg":"<CompletedOrder>{contract 25 0  Contract<CondID: 107113386, Symbol: FB, SecurityType: STK, Exchange: SMART, Currency: USD>} {order 25 0  Order<OrderID: 0, ClientID: 0, PermID: 1413528998> -- <MKT BUY 0.00@0.000000 DAY> --`

**Comment by hadrianl** [comment]
It seems that the completed order did not contain any info about orderID and ClientID.As for TotalQuantity and LimitPrice, I have reviewed the code and find out nothing wrong with it.
Maybe u could get your info via ExecDetails instead of CompletedOrder

**Comment by rcalin** [comment]
OK, thank you.
