### ISSUE TITLE
recover type inconsistent

### ISSUE THREAD

**Issue by travisgroth** [hadrianl/ibapi#19]
First, thanks for putting together this project!

I somehow got an error decoding a float the other day and the recovery code in `goDecode` failed.  It seems like the value passed to `panic()` from a zap logger Panic call is a string, not an error type.  Also after some experimentation, it _looks_ like if a NoOp logger is configured, the call to zap's Panic will just exit 0.

I was initially thinking of just adding a type check in the recieve/request/decode loops, but I'm actually wondering if all the logger panics should be changed to a standard golang panics instead.  This would allow the retry code to work and at least produce a stack trace rather than dying silently if I've disabled logging in the wrapper by setting it to NoOp.

Another option would be to do the type check and change the default wrapper log messages to debug so there's little temptation to set a NoOp logger.  

Thoughts?  I don't mind taking a pass at the change but I wanted to discuss an approach before putting together a PR.

**Comment by hadrianl** [comment]
@travisgroth Thanks for reporting this!It seems that we could panic the same type (`error` or `string`) to make it work. Type check might not be the best options.So, I think we got two options left:
- standard golang panic `error` or `string`
- zap logger panic `string`

Still, I do not understand the problem with `NoOp logger` yet!I will check the source code of zap later.
I think it\`s a better solution that replace all `panic(error)`, `panic(string)` into `zap.Panic(string)`

**Comment by travisgroth** [comment]
> Still, I do not understand the problem with NoOp logger yet!I will check the source code of zap later. 

Sorry, I just double checked and my testing was flawed.  Zap will still panic even with a NoOp logger.  You can ignore my commentary there.

Changing everything to a zap panic makes sense.  I can make a PR for that.
