### ISSUE TITLE
LoopUntilDone does not terminate on connection loss

### ISSUE THREAD

**Issue by travisgroth** [hadrianl/ibapi#22]
Hi,

I might be missing something, but I'm trying to wrap the connection and loop logic so that it can automatically retry when TWS or the api gateway are restarted.  It seems like `LoopUntilDone()` doesn't terminate when it loses the connection.  Instead of terminating, I get stuck in the goReceive code:

```
2021-02-02T22:45:24.260-0500    error   ibapi@v0.0.0-20210128031619-f0e8fffe1f4e/client.go:2895 receiver got unexpected error   {"error": "scanner Error"}
github.com/hadrianl/ibapi.(*IbClient).goReceive.func1
        github.com/hadrianl/ibapi@v0.0.0-20210128031619-f0e8fffe1f4e/client.go:2895
runtime.gopanic
        runtime/panic.go:969
go.uber.org/zap/zapcore.(*CheckedEntry).Write
        go.uber.org/zap@v1.16.0/zapcore/entry.go:234
go.uber.org/zap.(*Logger).Panic
        go.uber.org/zap@v1.16.0/logger.go:226
github.com/hadrianl/ibapi.(*IbClient).goReceive
        github.com/hadrianl/ibapi@v0.0.0-20210128031619-f0e8fffe1f4e/client.go:2927
2021-02-02T22:45:24.260-0500    panic   ibapi@v0.0.0-20210128031619-f0e8fffe1f4e/client.go:2927 scanner Error
github.com/hadrianl/ibapi.(*IbClient).goReceive
        github.com/hadrianl/ibapi@v0.0.0-20210128031619-f0e8fffe1f4e/client.go:2927
```

This message repeats forever.

I think the base issue is here:  https://github.com/hadrianl/ibapi/blob/master/client.go#L2919

Unlike `bufio.Reader`, `bufio.Scanner` returns nil upon `io.EOF`: https://golang.org/pkg/bufio/#Scanner.Scan

This is easily fixed and seems straightforward.  However, the `ic.Disconnect()` https://github.com/hadrianl/ibapi/blob/master/client.go#L2921 gets stuck on the wait group here https://github.com/hadrianl/ibapi/blob/master/client.go#L136 without further changes, because it is waiting on itself.

The naive approach is to call `ic.Disconnect` with a new goroutine, and that does work but I'm not sure that's really the right approach for how you want to be handling this case in the context of the rest of the code.  It definitely feels like a hack.  Here's a diff that demonstrates a potential fix https://github.com/hadrianl/ibapi/compare/master...travisgroth:disconnect_on_conn_loss?expand=1

Happy to open that as a PR or figure out a better way.  I haven't followed all the teardown code but I'm wondering if disconnect should just not call `ic.wg.Wait()`.

**Comment by hadrianl** [comment]
@travisgroth open a PR, let`s work with this.
