### ISSUE TITLE
Change client level to Debug 

### ISSUE THREAD

**Issue by marvin-hansen** [hadrianl/ibapi#24]
When running the sample code, I get a flood of logs on info level  that really should be better on debug level. 
Specifically,
* msg start / end 
* msg decoding 
* state change  

I understand, during development that level of detailed log helps. 

In practice, I suggest patching the util with a factory function that either returns or dev or production logger depending on some (enum) parameter, and the set the bulk of client logs to debug level. That way, people can at least switch log level easily without fiddling around with zap configs.

**Comment by benfrankstein** [comment]
hi. I am having trouble connecting to TWS with the sample code. Besides the socket port and master client ID is there anything else that needs to be changed? I confirmed that it is configured in my API settings on TWS already as well as added the same trusted IP.

**Comment by marvin-hansen** [comment]
@benfrankstein TWS is a quite bitchy to configure, so I suggest you to use the IB Gateway instead. 

I use a pre-build docker image for that: https://github.com/marvin-hansen/IB-gateway

Once you added your paper trading user name & password, just fire it up:

> cd ib-gateway-docker
> docker build .
> docker-compose up

Then you just run the copy & pasted sample code with client-id 0. Works out of the box for me. 

Note, when you overwrite the ibapi wrapper, you may want to create a factory function CreateNewIBApi that takes the wrapper interface as a parameter and returns a struct containing the initialized client. Reason is, you have to handle the connection on the call site anway so when passing the wrapper implementation as an argument, you can at least A/B test your implementation vs. the default (logging ) one so you can see the chain of events logged to the console. 

Best

**Comment by benfrankstein** [comment]
I was able to get the docker to run and I'm currently looking at the massive log haha. When I run the client sample on port 4003 with client 0 it tried to do the handshake and returns a refused connection error code 504. On the docker log it says "2021/02/12 13:49:08 socat[103] E connect(5, AF=2 127.0.0.1:4001, 16): Connection refused". From the start I've been having issues with connections, anything that you have found to be useful/work?

Thank you very much for your previous response 

:)

**Comment by marvin-hansen** [comment]
Have you created a separate paper trading account in the IB web admin?

Are you trying to use a live account in paper mode or other way around?
This always fails to login...

Have you disabled MFA security, that is, confirming login with with your
cell phone on that account?
This always prevents login and must be turned off..

Can you login with that account in tws with or without any issue or cell
phone confirmation?

Have you used vnc to check what exactly is happening on the gateway?
I

**Comment by benfrankstein** [comment]
hiya. Yea I created a paper trading account that I used on TWS. I set the account to paper mode and have been able to log in via scripting for a headless TWS startup from before. Security is all gone and good, even though I don't need it for paper trading. The only thing I haven't done is used the vnc with the gateway, but I did use it for TWS. I've been through about 4-5 packages and across golang and java and I always get stuck at the same handshake connection part. I always get error msg 504 "connection refused". I tried to remove the handshake and just go for a data request and I get the same issue. I am certain that I am able to connect to the port/gateway address though. I've also tried it both on a home linux server as well as an amazon EC2 instance. As for their API help, they didn't say much, basically repeated the instructions to me for an hour.

**Comment by marvin-hansen** [comment]
This is strange. Please install VNC and log into the gateway which should
show the login prompt. Then copy paste your login settings and press login.
If the things are fine, you should see the usual stuff.

The ENV settings in docker a prone to fail when there are unexpected blanks
or quotation marks.

Also, check if port 4003 is free before the gateway starts.

I post a bit later a working client that connects to the gateway, given
it's configured correctly and logs in.

**Comment by marvin-hansen** [comment]
@benfrankstein FYI, IB has a scheduled downtime so you can't login no matter what. 
I have the same issue with paper and live, so you have to wait until IB is back online. 

From the IB system status

"Due to scheduled system maintenance, clients will be unable to connect through our web, mobile, and TWS platforms."
[Mesg Id: 427]

https://www.interactivebrokers.com/en/software/systemStatus.php


That said, you find a working example client here:

https://github.com/marvin-hansen/ibGoClient

**Comment by hadrianl** [comment]
@marvin-hansen Thanks for your sugguestion!Later, I will start a PR to work on this. You might help with it if you are willing to!

**Comment by marvin-hansen** [comment]
@hadrianl  sounds good. Will draft a PR a bit later and submit for review.
