### ISSUE TITLE
Errors in PlaceOrder (PostToATS attribute)

### ISSUE THREAD

**Issue by smirnovalex** [hadrianl/ibapi#32]
I dot errors when trying to place an order (checked on both stock and future). It blocks order submission on latest TWS version
10274 The 'PostToATS' order attribute may not be specified for this order or is invalid.

I also have two warnings on sending order 
10983 Buy MKT 2168: Warning: The 'EtradeOnly' order attribute is not supported.
10983 Buy MKT 2169: Warning: The 'FirmQuoteOnly' order attribute is not supported.

Thanks for your work

**Comment by ddemoss222** [comment]
Getting these errors as well. Information on workarounds is hugely appreciated. Thanks.

**Comment by hadrianl** [comment]
OK！Fix it ASAP！

**Comment by hadrianl** [comment]
which tws version did you actually working on？

**Comment by ddemoss222** [comment]
985.1e

**Comment by hadrianl** [comment]
@smirnovalex @ddemoss222

**Comment by ddemoss222** [comment]
@hadrianl I can see trades going through on my terminal. I appreciate your swift action on this! Thank you
